apiVersion: v1
kind: ConfigMap
metadata:
# MetalLBを指定
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    # 名前をつける
    - name: web-service
      # プロトコルを指定（bgp or layer2）
      protocol: layer2
      # 自分の環境に合わせて設定してください
      addresses:
      - 10.0.1.111-10.0.1.250

