apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /Users/yamazato/Sites/kenshu/Kubernetes-exercise/data
    type: Directory

# apiVersion: v1
# kind: Pod
# metadata:
#   name: sample-pod
#   labels:
#     app: sample
# spec:
#   containers:
#   - name: sample
#     image: sample
#     command:
#     - tail
#     - -f
#     - /dev/null
#     volumeMounts:
#     - name: app
#       mountPath: /app
#   volumes:
#   - name: app
#     hostPath:
#     # ここは現在のディレクトリに変える
#       path: /Users/user/path/to/app
#       type: Directory

# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: pv-nfs
#   labels:
#     type: nfs
# spec:
#   capacity:
#     storage: 30Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   nfs:
#     path: /Users/yamazato/Sites/kenshu/Kubernetes-exercise/data
#     server: 192.168.99.108

# apiVersion: v1  ##「表１PersistentVolumeClaim v1 core」
# kind: PersistentVolumeClaim
# metadata:       ##「表2 ObjectMeta v1 meta」
#   name: data1
# spec:           ##「表3 PersistentVolumeClaimSpec v1 core」
#   accessModes:
#   - ReadWriteOnce
#   storageClassName: standard
#   resources:
#     requests:
#       storage: 2Gi