apiVersion: apps/v1
# kind: デプロイメントを指定します
kind: Deployment

# デプロイメントの名前を指定します
metadata:
  name: ocw2-deployment

# spec: デプロイメントの仕様を記述します。
spec:

# ポッドテンプレート（雛形）を使って起動するポッド数（レプリカ数）を指定します。
# この数を変更することでスケールさせることができます。
  replicas: 1

# レプリカセットとポッドテンプレートの対応づけを行います。
# matchLabels のラベル（app: web）とポッドテンプレートのラベル（app: web）は一致させなければなりません。
  selector:
    matchLabels:
      app: web3

# ポッドテンプレートの仕様を記述します。
# 仕様はロールアウト機能で変更できます（バージョンアップ）    
  template:
    metadata:
      labels:
        app: web3 # ポッドのラベル
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        # image: nginx #　latestは指定しない方が良い。バージョンを指定しない場合、latestになる。
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ocw2-service
# spec:
#   selector:
#     app: liberty
#   ports:
#      -  port: 8090
#         targetPort: 8090

apiVersion: v1
kind: Service
metadata:
  name: ocw2-service
spec:
  type: NodePort
  ports:
     -  port: 8090
        protocol: TCP
        targetPort: 80
        nodePort: 31465
  selector:
    app: web3

